### ISSUE TITLE
[Project][Github運用]各リポジトリのAbout欄のトピックを設定する

### ISSUE THREAD

**Issue by shimajima-eiji** [shimajima-eiji/__Github-Operation#22]
### プロジェクト
- #1

### 前提タスク
- #なし

### 関連タスク
- #なし

### Issueテンプレートバージョン
- 2021/12/24(https://github.com/shimajima-eiji/Projects/commit/0e009fce8b327651a30b32b5b5dd2d79b20a351d)

---

## なぜやるのか
アクセス数を増やすのと、どういうリポジトリなのか情報を捕捉する

### 現状
https://github.com/shimajima-eiji/README に参考例

### 解決案、または影響があるファイル
このリポジトリだと、 https://github.com/shimajima-eiji/Projects のAbout欄から設定できる

**Comment by shimajima-eiji** [comment]
テンプレート
https://github.com/shimajima-eiji/__Github-Operation/wiki/T:-%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA

**Comment by KatsuyaNakano** [comment]
aaa

**Comment by shimajima-eiji** [comment]
リポジトリを減らしたいのでやらない
